project:
  type: website

website:
  title: "Miguel de Navascués --- Population Genetics"
  site-url: "https://mnavascues.github.io/Website/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: News.qmd
        text: "News"
      - href: Films.qmd
        text: "Films"
      - href: ShortCV.qmd
        text: "Short CV"
      - href: FullCV.qmd
        text: "Full CV"
      - href: Contact.qmd
        text: "Contact"

format:
  html:
    code-fold: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-title: Contents
    link-external-icon: true
    link-external-newwindow: true
    other-links:
      - text: ORCID
        icon: person-circle
        href: http://orcid.org/0000-0001-8342-6047
      - text: OpenAlex
        icon: person-circle
        href: https://openalex.org/authors/a5008213968
      - text: GitHub
        icon: github
        href: https://github.com/mnavascues
      - text: Mastodon
        icon: mastodon
        href: https://mastodon.online/@Miguel_de_Navascues
      - text: CBGP
        icon: person-workspace
        href: https://umr-cbgp.fr/membre/de-navascues/
  pdf:
    geometry: 
      - top=20mm
      - left=20mm
      - right=20mm
      - nohead
      - nofoot
editor: source



